RoomSceduler/Models/Rooms/AvailableRoomsViewModel.cs
namespace RoomSceduler.Models.Rooms
{
    public class AvailableRoomsViewModel
    {
        public string AvailableRooms { get; set; }

        public string Date { get; set; }

        public string TimeInterval { get; set; }

        public string RoomName { get; set; }
    }
}

RoomSceduler/Models/Rooms/CheckRoomFormModel.cs
namespace RoomSceduler.Models.Rooms
{
    public class CheckRoomFormModel
    {
        public string Date { get; set; }

        public int NumberOfPartisipants { get; set; }

        public int MeetingDuration { get; set; }
    }
}

RoomSceduler/Models/Rooms/RoomAvailableIntervalsModel.cs
using System;

namespace RoomSceduler.Models.Rooms
{
    public class RoomAvailableIntervalsModel
    {
        public DateTime From { get; set; }

        public DateTime To { get; set; }

        public TimeSpan AvialebleTime { get; set; }
    }
}

RoomSceduler/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RoomSceduler.Data;
using RoomSceduler.Data.Models;
using RoomSceduler.Models.Rooms;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RoomSceduler.Controllers
{

    public class RoomsController: Controller
    {

        private ApplicationDbContext db;
        
        public RoomsController(ApplicationDbContext db)
        {
            this.db = db;
        }

        public IActionResult CheckRoom()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CheckRoom(CheckRoomFormModel check)
        {
            var roomsString = System.IO.File.ReadAllText("wwwroot/Input/input.json");

            var rooms = JsonConvert.DeserializeObject<List<RoomJsonModel>>(roomsString);

            var availableRooms = rooms
                .Where(x => x.Capacity >= check.NumberOfPartisipants)
                .ToList();

            var sb = new StringBuilder();

            foreach (var room in availableRooms)
            {
                sb.AppendLine($"{room.RoomName} -");

                var date1 = false;

                foreach (var item in room.Schedule)
                {
                    var sbt = item.From.Substring(0, 10);
                    date1 = sbt == check.Date;
                    if (date1)
                    {
                        break;
                    }
                }

                if ( !date1 )
                {
                    var roomOpeningDatetime = DateTime
                        .Parse( $"{check.Date} T {room.AvailableFrom}");

                    var roomClosingDatetime = DateTime
                        .Parse(check.Date + "T" + room.AvailableTo);

                    while (true)
                    {
                        var FirstTimeRoomIsAvailableFrom = roomOpeningDatetime;
                        var RoomIsAvailableTo = roomOpeningDatetime
                            .AddMinutes(check.MeetingDuration);

                        var FirstTimeRoomIsAvailable = $"{FirstTimeRoomIsAvailableFrom.ToString("yyyy-MM-dd HH:mm:ss")} -- {RoomIsAvailableTo.ToString("yyyy-MM-dd HH:mm:ss")} || ";

                        sb.AppendLine(FirstTimeRoomIsAvailable);

                        var FirstTimeRoomIsAvailableFromPlusFifteen =
                                FirstTimeRoomIsAvailableFrom.AddMinutes(15);

                        while (true)
                        {
                            if (FirstTimeRoomIsAvailableFromPlusFifteen.AddMinutes(check.MeetingDuration) >= roomClosingDatetime)
                            {
                                break;
                            }

                            var firstTostr = FirstTimeRoomIsAvailableFromPlusFifteen.ToString("yyyy-MM-dd HH:mm:ss");

                            var firstPlus15PlusDuraion = FirstTimeRoomIsAvailableFromPlusFifteen.AddMinutes(check.MeetingDuration)
                            .ToString("yyyy-MM-dd HH:mm:ss");
                             
                            var nextTimeInterval = $"{firstTostr} -- {firstPlus15PlusDuraion} ";

                            sb.AppendLine($"{nextTimeInterval} || ");
                            sb.AppendLine();
                            FirstTimeRoomIsAvailableFromPlusFifteen = FirstTimeRoomIsAvailableFromPlusFifteen.AddMinutes(15);
                        }
                        break;
                    }
                }
                else
                {
                    var roomOpeningDatetime = DateTime
                        .Parse($"{check.Date} T {room.AvailableFrom}");


                    var datetimeRoomSchedules = room.Schedule
                        .Select(x => new TimeSlotSort
                        {
                            From = DateTime.Parse(x.From),
                            To = DateTime.Parse(x.To)
                        }).ToList();

                    datetimeRoomSchedules = datetimeRoomSchedules
                        .OrderBy(x => x.From)
                        .ToList();

                    var firstAvialebleInterval = datetimeRoomSchedules[0].From - roomOpeningDatetime;

                    if (firstAvialebleInterval.TotalMinutes >= check.MeetingDuration)
                    {
                        var roomOpeningTimePlusFifteen = roomOpeningDatetime.AddMinutes(15);

                        while (true)
                        {
                            var RoomIsAvailableTo = roomOpeningDatetime
                                .AddMinutes(check.MeetingDuration);

                            var FirstTimeRoomIsAvailable = $"{roomOpeningDatetime.ToString("yyyy-MM-dd HH:mm:ss")} -- {RoomIsAvailableTo.ToString("yyyy-MM-dd HH:mm:ss")}  || ";

                            sb.AppendLine(FirstTimeRoomIsAvailable);

                            while (true)
                            {
                                if (roomOpeningTimePlusFifteen.AddMinutes(check.MeetingDuration) > datetimeRoomSchedules[0].From)
                                {
                                    break;
                                }

                                var nextTimeRoomIsAvailable = $"{roomOpeningTimePlusFifteen.ToString("yyyy-MM-dd HH:mm:ss").Substring(12)} -- {roomOpeningTimePlusFifteen.AddMinutes(check.MeetingDuration).ToString("yyyy-MM-dd HH:mm:ss")} || ";

                                roomOpeningTimePlusFifteen = roomOpeningTimePlusFifteen.AddMinutes(15);
                                sb.AppendLine(nextTimeRoomIsAvailable);
                            }

                            break;
                        }

                    }

                    var freeIntervalsList = new List<RoomAvailableIntervalsModel>();
                    for (int i = 0; i < datetimeRoomSchedules.Count -1; i++)
                    {
                        var roomFreeInterval = datetimeRoomSchedules[i + 1].From - datetimeRoomSchedules[i].To;

                        if (roomFreeInterval.TotalMinutes >= check.MeetingDuration)
                        {
                            var freeInterval = new RoomAvailableIntervalsModel
                            {
                                From = datetimeRoomSchedules[i].To,
                                To = datetimeRoomSchedules[i + 1].From,
                                AvialebleTime = roomFreeInterval
                            };

                            freeIntervalsList.Add(freeInterval);
                        }
                    }

                    foreach (var interval in freeIntervalsList)
                    {
                        var firstTimeRoomIsAvialeble = $"{interval.From.ToString("yyyy-MM-dd HH:mm:ss")} -- {interval.From.AddMinutes(check.MeetingDuration).ToString("yyyy-MM-dd HH:mm:ss")} || ";

                        sb.AppendLine(firstTimeRoomIsAvialeble);

                        var firstTimeRoomIsAvialeblePlusFifteen = interval.From.AddMinutes(check.MeetingDuration + 15);
                        while (true)
                        {
                            if (firstTimeRoomIsAvialeblePlusFifteen > interval.To)
                            {
                                break;
                            }

                            var nextTimeRoomIsAvialeble = $"{firstTimeRoomIsAvialeblePlusFifteen.ToString("yyyy - MM - dd HH: mm: ss")} -- {firstTimeRoomIsAvialeblePlusFifteen.AddMinutes(check.MeetingDuration).ToString("yyyy-MM-dd HH:mm:ss")} || ";

                            sb.AppendLine(nextTimeRoomIsAvialeble);

                            firstTimeRoomIsAvialeblePlusFifteen = firstTimeRoomIsAvialeblePlusFifteen.AddMinutes(15);
                        }
                    }
                                                           
                }
            }

            var model = new AvailableRoomsViewModel
            {
                AvailableRooms = sb.ToString()
            };

            return View("AvailableRooms",model);
        }

        public IActionResult InsertTimeInterval(AvailableRoomsViewModel model)
        {
            var roomsString = System.IO.File.ReadAllText("wwwroot/Input/input.json");

            var rooms = JsonConvert.DeserializeObject<List<RoomJsonModel>>(roomsString);

            var roomToModify = rooms.FirstOrDefault(x => x.RoomName == model.RoomName);

            rooms.Remove(roomToModify);

            var startHour = model.TimeInterval.Substring(0, 22);
            var endHour = model.TimeInterval.Substring(25);

            var timeslot = new TimeSlotJsonModel
            {
                From = startHour.ToString(),
                To = endHour
            };

            roomToModify.Schedule.Add(timeslot);
            rooms.Add(roomToModify);

            var jsonString = JsonConvert.SerializeObject(rooms,Formatting.Indented);

            System.IO.File.WriteAllText("wwwroot/Input/input.json", jsonString);

            return RedirectToAction("Index", "Home");
        }
    }


}

RoomSceduler/Views/Rooms/AvailableRooms.cshtml
@using RoomSceduler.Models.Rooms

@model AvailableRoomsViewModel

@{
    ViewData["Title"] = "Available Rooms";
}
<div class="mb-1">
    <p> @Model.AvailableRooms</p>     
</div>
<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <h2 class="heading-margin text-center">Copy and Paste Time Interval Here</h2>
        <form method="post" asp-controller="Rooms" asp-action="InsertTimeInterval">
            <div class="form-group">
                <label asp-for="RoomName"></label>
                <input asp-for="RoomName" class="form-control" placeholder="Copy time interval here">
                <span asp-validation-for="RoomName" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeInterval"></label>
                <input asp-for="TimeInterval" class="form-control" placeholder="Copy time interval here">
                <span asp-validation-for="TimeInterval" class="small text-danger"></span>
            </div>
            <input class="btn btn-primary" type="submit" value="Submit"/>
        </form>
    </div>
</div>

RoomSceduler/Views/Rooms/CheckRoom.cshtml
@using RoomSceduler.Models.Rooms

@model CheckRoomFormModel

@{
    ViewData["Title"] = "Check Room";
}

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <h2 class="heading-margin text-center">Check Room</h2>
        <form method="post">
            <div class="form-group">
                <label asp-for="Date"></label>
                <input asp-for="Date" class="form-control" placeholder="Enter date here">
                <span asp-validation-for="Date" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfPartisipants"></label>
                <input asp-for="NumberOfPartisipants" class="form-control" placeholder="Enter number of participants here">
                <span asp-validation-for="NumberOfPartisipants" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeetingDuration"></label>
                <input asp-for="MeetingDuration" class="form-control" placeholder="Enter meeting duration in minutes here">
                <span asp-validation-for="MeetingDuration" class="small text-danger"></span>
            </div>
            <input class="btn btn-primary" type="submit" value="Check" />
        </form>
    </div>
</div>